//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_Tracking_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int announcement_id { get; set; }
        public string announcement1 { get; set; }
        public Nullable<System.DateTime> announcement_date { get; set; }
        public string mentor_email_fk { get; set; }
        public string supervisor_email_fk { get; set; }
    
        public virtual Mentor Mentor { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
